### PR TITLE
Add AndroidX Support

### PR DESCRIPTION
**Pull request by PR1YANKPAT3L**

### CODE REVIEW

**Comment by josh-m-sharpe** [comment]
@PR1YANKPAT3L 

Should these things be migrated too?

grep -R android.*support android/
android//capacitor-fcm/build.gradle:        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
android//capacitor-fcm/build.gradle:    androidTestImplementation 'com.android.support.test:runner:1.0.1'
android//capacitor-fcm/build.gradle:    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
android//capacitor-fcm/build.gradle:    androidTestImplementation 'com.android.support:support-annotations:28.0.0'
android//capacitor-fcm/build.gradle:    implementation 'com.android.support:appcompat-v7:28.0.0'
android//capacitor-fcm/src/androidTest/java/com/getcapacitor/android/ExampleInstrumentedTest.java:import android.support.test.InstrumentationRegistry;
android//capacitor-fcm/src/androidTest/java/com/getcapacitor/android/ExampleInstrumentedTest.java:import android.support.test.runner.AndroidJUnit4;

**Comment by stewwan** [comment]
hey @PR1YANKPAT3L thanks for your PR, I really tried to test it but no luck. it seems to be not fully supported yet

**Comment by stewwan** [comment]
I think it's better to wait till capacitor 2.0

**Comment by josh-m-sharpe** [comment]
@PR1YANKPAT3L Do you think those things in my comment should have also been migrated?

**Pull request merged**
